#!/usr/bin/env bash

#
# @module php functions
#

#
# Parse php version and export variables to the global scope.
# 
# string $1 php version.
#
# USAGE
# php_parse_version_from_string '5.3.6'
php_parse_version_from_string()
{
  PHP_VERSION=$1
  PHP_VMAJOR=`echo ${PHP_VERSION%%.*}`
  PHP_VMINOR=`echo ${PHP_VERSION%.*}`
  PHP_VMINOR=`echo ${PHP_VMINOR#*.}`
  PHP_VPATCH=`echo ${PHP_VERSION##*.}`
}

#
# Download and parse the available php source files.
# 
# string $1 server url with the anchors to the php source files.
#
# USAGE
# php_parse_versions_from_url 'http://museum.php.net/php4/'
# php_parse_versions_from_url 'http://museum.php.net/php5/'
php_parse_versions_from_url()
{
  curl -f -s -L $1 | sed -nE 's|^.*href="(php-[^"]+)".*$|\1| p'  
}

#
# Build the php version given a php version as parameter.
# 
# string $1 PHP version should be downloaded + compiled + installed locally.
#
install_php()
{
  # php source directory
  srcdir="$TMP_DIR/php-$PHP_VERSION"

  # php install directory
  instdir="$INSTALL_DIR/php-$PHP_VERSION"

  ### download php source
  if [ ! -d "$srcdir" ]; then

      echo -e "\033[1mDownloading $PHP_VERSION source code\033[0m"

      srcfile="$CACHE_DIR/php-$PHP_VERSION.tar.bz2"
      
      if [ ! -f "$srcfile" ]; then
          url=$(macro $PHP_MUSEUM '%%PHP_MAYOR%%' $PHP_VMAJOR)
          url=$(macro $url '%%PHP_VERSION%%' $PHP_VERSION)
          wget -P "$CACHE_DIR" "$url"
          
          if [ ! -f "$srcfile" ]; then
              url=$(macro $PHP_GET '%%PHP_VERSION%%' $PHP_VERSION)
              wget -P "$CACHE_DIR" -O "$srcfile" "$url"
          fi

          if [ ! -f "$srcfile" ]; then
              echo "Fetching sources failed:"
              echo $url
              exit 2
          fi
      fi
   
      cd $TMP_DIR
      echo -e "\033[1mUncompressing source code\033[0m"
      tar xjf "$srcfile"
      cd $BASE_DIR
  fi

  ### load ./configure parameters
  source 'options.sh' "$PHP_VERSION" "$PHP_VMAJOR" "$PHP_VMINOR" "$PHP_VPATCH"
  cd "$srcdir"
 
  echo -e "\033[1m./configure\033[0m"

  ### run ./configure
  ./configure \
   --prefix="$instdir" \
   --exec-prefix="$instdir" \
   --enable-debug \
   --disable-short-tags \
   --without-pear \
   $configoptions

  if [ $? -gt 0 ]; then
      echo configure.sh failed.
      exit 3
  fi

  echo -e "\033[1mmake\033[0m"
  ### run make
  make
  if [ "$?" -gt 0 ]; then
      echo make failed.
      exit 4
  fi

  confirm "Are you sure you want to install here: $instdir?"
  if [ $? -eq 1 ]; then
    exit 0
  fi

  echo -e "\033[1mmake install\033[0m"
  ### run make install
  make install
  if [ "$?" -gt 0 ]; then
      echo make install failed.
      exit 5
  fi

  echo -e "\033[1mCopy php.ini to lib directory\033[0m"
  ### copy default php.ini to config directory 
  
  for file in "$srcdir/php.ini*"
  do
    cp $file "$instdir/lib/"
  done
}

# 
# Remove an existent php version from the system.
# 
uninstall_php()
{
  local dst="$INSTALL_DIR/php-$PHP_VERSION"

  if [ -d "$dst" ]; then
    confirm "Are you sure you want to delete $dst?"
    if [ $? -eq 0 ]; then
      rm -rf "$dst"
    fi
  fi
}

#
# Set the current environment using the given version.
#
set_current_php()
{
  local root="$INSTALL_DIR/php-$PHP_VERSION"

  # clean bin directory
  rm $BIN_DIR/*

  # create the symlinks
  for file in "$root/bin/*"
  do
    ln -s $file $BIN_DIR
  done
}

#
# Show the system php default version
#
show_current_settings()
{
  php -v
}

#
# Show restore instructions.
#
restore_default_settings()
{
cat <<EOM
In order to restore your default configuration:
  1 - Update your .bashrc and remove the line which define '$BIN_DIR'.
  2 - Optional you can just remove the pvm folder.
EOM
}

#
# Show available php versions using local file or download it from github
#
list_available_php()
{
  curl -f -L $PHP_VERSIONS
}

#
# Show installed php versions
#
list_installed_php()
{
  echo -e "\033[1mInstalled PHP versions:\033[0m"
  ls $INSTALL_DIR | tr "\t" "\n"
}
