#!/usr/bin/env bash

### PVM global paths

#
BASE_DIR="$( cd "$( dirname "$0" )" && pwd )"

#
CORE_DIR="$BASE_DIR/core"

#
MODULES_DIR="$BASE_DIR/modules"

#
BIN_DIR="$BASE_DIR/bin"

#
INSTALL_DIR="$BASE_DIR/install"

# 
CACHE_DIR="$BASE_DIR/cache"

#
TMP_DIR="$BASE_DIR/tmp"

### PHP download urls

# remote source 
PHP_MUSEUM="http://museum.php.net/php%%PHP_MAYOR%%/php-%%PHP_VERSION%%.tar.bz2"

# remote source
PHP_GET="http://www.php.net/get/php-%%PHP_VERSION%%.tar.bz2/from/this/mirror"

# TODO
# create gh-pages on github with the php available versions
PHP_VERSIONS_FILE=versions
PHP_VERSIONS="http://dendril.github.com/pvm/core/$PHP_VERSIONS_FILE"
