#!/usr/bin/env bash

### PVM global paths

# Base directory
BASE_DIR="$( cd "$( dirname "$0" )" && pwd )"

# Core directory
CORE_DIR="$BASE_DIR/core"

# Modules directory
MODULES_DIR="$BASE_DIR/modules"

# Binary directory
BIN_DIR="$BASE_DIR/bin"

# Instalation directory
INSTALL_DIR="$BASE_DIR/install"

# Cache directory
CACHE_DIR="$BASE_DIR/cache"

# Temporal directory
TMP_DIR="$BASE_DIR/tmp"

### PHP download mirrors

# remote source
PHP_MUSEUM="http://museum.php.net/php%%PHP_MAYOR%%/php-%%PHP_VERSION%%.tar.bz2"

# remote source
PHP_GET="http://www.php.net/get/php-%%PHP_VERSION%%.tar.bz2/from/this/mirror"

# gh-pages on github where we have the php available versions
PHP_VERSIONS_FILE=versions
PHP_VERSIONS="http://dendril.github.com/pvm/$PHP_VERSIONS_FILE"
