#!/usr/bin/env bash

### PVM global paths

# Core directory
CORE_DIR="$PWD/core"

# Modules directory
MODULES_DIR="$PWD/modules"

# Binary directory
BIN_DIR="$PWD/bin"

# Instalation directory
INSTALL_DIR="$PWD/install"

# Cache directory
CACHE_DIR="$PWD/cache"

# Temporal directory
TMP_DIR="$PWD/tmp"

### PHP download mirrors

# remote source
PHP_MUSEUM="http://museum.php.net/php%%PHP_MAYOR%%/php-%%PHP_VERSION%%.tar.bz2"

# remote source
PHP_GET="http://www.php.net/get/php-%%PHP_VERSION%%.tar.bz2/from/this/mirror"

# gh-pages on github where we have the php available versions
PHP_VERSIONS_FILE=versions
PHP_VERSIONS="http://dendril.github.com/pvm/$PHP_VERSIONS_FILE"
